server:
  port: 9090
  servlet:
    context-path: /api/integradorrecaudo

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/integradorrecaudo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      minimum-idle: 1
      maximum-pool-size: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults:
        dialect: org.hibernate.dialect.PostgresPlusDialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

  mail:
      host: smtp.mandrillapp.com
      username: mensajes@playtechla.com
      password: md-6k8KhHJ-tOCaeW7Hnt9YgA
      port: 587
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
              required: true

correo: desarrollolisto@playtechla.com
correos-envio: mensajes@listoonline.co

security:
  jwt:
    user:
      generator: AUTH0JWT-BACKEND
    key:
      private: MIICWwIBAAKBgQCtYo32glu50D5XU3e7jk5RW3OvmmSIA4RxvS2N7acGixkvRkkn2yIGQXGhMmWzU6dT4gKEdsdJugP7iv5ornIs+VNLzunXLGu+qTHeG5BQJneugeTdSNZsu4cf7j0XrHo0mDONExkvKiXsG32XqqZ/8QJx9WZA3U+QV4JHrHd82wIDAQABAn8ArWHglKHHGAkmTi0pjmS/7JuHFBNQdLMPvq1u4H7Gh8SRarTecvyvCZJoDspW6Py+VyOrYMtmflOFqAVWY1gO00QrvPO93iuy5dQCQGZ64qmDjWaozOdnf73C2ZFaWcw052ReKRvPvoVoQYrhTN6ALcL5/Pw1J/oQ/Cf5XXB5AkEA4XIV80lGISHEB8vMAe02bMN+g04k8RpzloqS78ILcW7NfP3aC0Yiu4eN52epFkUNnwv1OG5VSxTs36ahUDCe3wJBAMTiNLwlvyG46Rp9/bDn0JVN+RRghMeHkf+59apHIRR8s4HwJY3aMhl3l0DzFtSUZg7OvMbFx2MBrT7mIPJwbYUCQQC6kguQVuduq97rBMFEJuePgwnD6Hux/E4EG5IWUOPfb+8mrX4xLk24HCpXgvXvtB3drau2k7iKdjrBq8h78IDJAkAfUwom4S6Os/fKcj85tTg3eQdnGZAmmsg80p5mcBiwRMLeqpGfBxcvfBqBh+ua+N1f/76DNZZqhyrENiMJz59tAkEAkbjouc73fd5LPaOH/4cAyAHTIfKaOIoq5l97a1ttm9sec5hb7AylfG/Z8sluHWNtMCf01LR6t+NmHtVsACorbg==

springdoc:
  swagger-ui:
    path: /swagger-ui.html

archivos:
  ubicacion: D:\Desarrollo\integrador_recaudo\Servidor\Core\integradorrecaudo\logsBD
