#server:
#  port: 9090
spring:
  application:
    name: msvc-credito
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: postgres
#    url: jdbc:postgresql://localhost:5434/creditodb
#  jpa:
#    hibernate:
#      ddl-auto: create
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:configserver:http://localhost:8888

#eureka:
#  instance:
#    hostname: localhost
#  client:
#    eureka-server-u-r-l-context: http://locahost:8761/eureka/

