#server:
#  port: 8080

spring:
  application:
    name: msvc-gateway
  config:
    import: optional:configserver:http://localhost:8888
#  security:
#    oauth2:
#      client:
#        registration:
#          keycloak:
#            client-id: microservicio_cliente
#            client-secret: WzOLxe0j23oWPmdGpTUmpQgHjUDFWfiV
#            client-name: keycloak
#            authorization-grant-type: authorization_code
#            redirect-uri: /realms/mymicroservicios-realm/account/*
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8181/realms/mymicroservicios-realm



#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      routes:
#        - id: cliente
#          uri:
#            http://localhost:8090
#          predicates:
#            - Path=/cliente/**
#        - id: credito
#          uri:
#            http://localhost:9090
#          predicates:
#            - Path=/credito/**




