#server:
#  port: 8080

spring:
  application:
    name: msvc-gateway
  config:
    import: optional:configserver:http://localhost:8888
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      routes:
#        - id: cliente
#          uri:
#            http://localhost:8090
#          predicates:
#            - Path=/cliente/**
#        - id: credito
#          uri:
#            http://localhost:9090
#          predicates:
#            - Path=/credito/**




